In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.DataFrame(np.array([[32,30,41,69,52], [56,26,57,38,32], [5,60,16,32,3], [35,52,40,18,47], [7,80,1,87,2], [13,32,2,85,16], [79,3,38,53,14], [56,24,59,32,12], [72,26,87,6,67], [14,83,43,48,20], [1,64,63,48,13], [18,72,40,46,21], [76,52,67,61,8], [10,49,57,20,15], [25,90,46,24,43], [31,66,90,25,61], [45,47,53,32,38], [4,85,34,64,43], [49,7,11,46,3]]), columns=list('ABCDE'))

In [3]:
df.head

<bound method NDFrame.head of      A   B   C   D   E
0   32  30  41  69  52
1   56  26  57  38  32
2    5  60  16  32   3
3   35  52  40  18  47
4    7  80   1  87   2
5   13  32   2  85  16
6   79   3  38  53  14
7   56  24  59  32  12
8   72  26  87   6  67
9   14  83  43  48  20
10   1  64  63  48  13
11  18  72  40  46  21
12  76  52  67  61   8
13  10  49  57  20  15
14  25  90  46  24  43
15  31  66  90  25  61
16  45  47  53  32  38
17   4  85  34  64  43
18  49   7  11  46   3>

In [4]:
df.duplicated().sum() 

0

In [5]:
X = df.iloc[:].values
y = df.iloc[:].values
print(X)

print(y)

[[32 30 41 69 52]
 [56 26 57 38 32]
 [ 5 60 16 32  3]
 [35 52 40 18 47]
 [ 7 80  1 87  2]
 [13 32  2 85 16]
 [79  3 38 53 14]
 [56 24 59 32 12]
 [72 26 87  6 67]
 [14 83 43 48 20]
 [ 1 64 63 48 13]
 [18 72 40 46 21]
 [76 52 67 61  8]
 [10 49 57 20 15]
 [25 90 46 24 43]
 [31 66 90 25 61]
 [45 47 53 32 38]
 [ 4 85 34 64 43]
 [49  7 11 46  3]]
[[32 30 41 69 52]
 [56 26 57 38 32]
 [ 5 60 16 32  3]
 [35 52 40 18 47]
 [ 7 80  1 87  2]
 [13 32  2 85 16]
 [79  3 38 53 14]
 [56 24 59 32 12]
 [72 26 87  6 67]
 [14 83 43 48 20]
 [ 1 64 63 48 13]
 [18 72 40 46 21]
 [76 52 67 61  8]
 [10 49 57 20 15]
 [25 90 46 24 43]
 [31 66 90 25 61]
 [45 47 53 32 38]
 [ 4 85 34 64 43]
 [49  7 11 46  3]]


In [6]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [8]:
r.score(X, y)

1.0

In [9]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[32. 30. 41. 69. 52.]
 [13. 32.  2. 85. 16.]
 [18. 72. 40. 46. 21.]
 [56. 26. 57. 38. 32.]]


In [6]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=32)

In [7]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [8]:
r.score(X, y)

1.0

In [11]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[79.  3. 38. 53. 14.]
 [49.  7. 11. 46.  3.]
 [76. 52. 67. 61.  8.]
 [32. 30. 41. 69. 52.]]


In [12]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=31)

In [13]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[31. 66. 90. 25. 61.]
 [ 7. 80.  1. 87.  2.]
 [32. 30. 41. 69. 52.]
 [35. 52. 40. 18. 47.]]


In [15]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)

In [16]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [17]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[ 1. 64. 63. 48. 13.]
 [32. 30. 41. 69. 52.]
 [25. 90. 46. 24. 43.]
 [18. 72. 40. 46. 21.]]


In [18]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=32)

In [19]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [20]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[79.  3. 38. 53. 14.]
 [49.  7. 11. 46.  3.]
 [76. 52. 67. 61.  8.]
 [32. 30. 41. 69. 52.]]


In [21]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=33)

In [22]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [23]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[31. 66. 90. 25. 61.]
 [72. 26. 87.  6. 67.]
 [10. 49. 57. 20. 15.]
 [ 4. 85. 34. 64. 43.]]


In [24]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=34)

In [25]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [26]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[76. 52. 67. 61.  8.]
 [45. 47. 53. 32. 38.]
 [32. 30. 41. 69. 52.]
 [49.  7. 11. 46.  3.]]


In [27]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=35)

In [28]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [29]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[ 4. 85. 34. 64. 43.]
 [ 5. 60. 16. 32.  3.]
 [10. 49. 57. 20. 15.]
 [13. 32.  2. 85. 16.]]


In [30]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=36)

In [31]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [32]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[10. 49. 57. 20. 15.]
 [45. 47. 53. 32. 38.]
 [ 4. 85. 34. 64. 43.]
 [18. 72. 40. 46. 21.]]


In [33]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=37)

In [34]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [35]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[56. 26. 57. 38. 32.]
 [14. 83. 43. 48. 20.]
 [ 5. 60. 16. 32.  3.]
 [ 7. 80.  1. 87.  2.]]


In [36]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=38)

In [37]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [38]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[10. 49. 57. 20. 15.]
 [72. 26. 87.  6. 67.]
 [13. 32.  2. 85. 16.]
 [ 4. 85. 34. 64. 43.]]


In [39]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=39)

In [40]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [41]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[13. 32.  2. 85. 16.]
 [76. 52. 67. 61.  8.]
 [ 5. 60. 16. 32.  3.]
 [ 1. 64. 63. 48. 13.]]


In [42]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [43]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [44]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[45. 47. 53. 32. 38.]
 [ 1. 64. 63. 48. 13.]
 [ 7. 80.  1. 87.  2.]
 [32. 30. 41. 69. 52.]]


In [45]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41)

In [47]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [48]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[79.  3. 38. 53. 14.]
 [10. 49. 57. 20. 15.]
 [18. 72. 40. 46. 21.]
 [ 7. 80.  1. 87.  2.]]


In [49]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [50]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [51]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[32. 30. 41. 69. 52.]
 [13. 32.  2. 85. 16.]
 [18. 72. 40. 46. 21.]
 [56. 26. 57. 38. 32.]]


In [52]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=43)

In [53]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [54]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[14. 83. 43. 48. 20.]
 [79.  3. 38. 53. 14.]
 [49.  7. 11. 46.  3.]
 [25. 90. 46. 24. 43.]]


In [55]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=44)

In [56]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [57]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[45. 47. 53. 32. 38.]
 [13. 32.  2. 85. 16.]
 [ 5. 60. 16. 32.  3.]
 [76. 52. 67. 61.  8.]]


In [58]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [59]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [60]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[56. 24. 59. 32. 12.]
 [49.  7. 11. 46.  3.]
 [ 5. 60. 16. 32.  3.]
 [76. 52. 67. 61.  8.]]


In [61]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=46)

In [62]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [63]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[56. 26. 57. 38. 32.]
 [14. 83. 43. 48. 20.]
 [49.  7. 11. 46.  3.]
 [ 7. 80.  1. 87.  2.]]


In [64]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=47)

In [65]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [66]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[ 1. 64. 63. 48. 13.]
 [10. 49. 57. 20. 15.]
 [ 4. 85. 34. 64. 43.]
 [ 7. 80.  1. 87.  2.]]


In [67]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [68]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [69]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[56. 26. 57. 38. 32.]
 [45. 47. 53. 32. 38.]
 [ 1. 64. 63. 48. 13.]
 [13. 32.  2. 85. 16.]]


In [70]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=49)

In [71]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [72]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[14. 83. 43. 48. 20.]
 [49.  7. 11. 46.  3.]
 [25. 90. 46. 24. 43.]
 [35. 52. 40. 18. 47.]]


In [73]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

In [74]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [75]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[25. 90. 46. 24. 43.]
 [72. 26. 87.  6. 67.]
 [14. 83. 43. 48. 20.]
 [ 4. 85. 34. 64. 43.]]


In [76]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [77]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [78]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[56. 26. 57. 38. 32.]
 [18. 72. 40. 46. 21.]
 [25. 90. 46. 24. 43.]
 [ 5. 60. 16. 32.  3.]]


In [79]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=52)

In [80]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [81]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[ 7. 80.  1. 87.  2.]
 [ 5. 60. 16. 32.  3.]
 [56. 24. 59. 32. 12.]
 [45. 47. 53. 32. 38.]]


In [82]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=53)

In [83]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [84]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[56. 24. 59. 32. 12.]
 [32. 30. 41. 69. 52.]
 [18. 72. 40. 46. 21.]
 [10. 49. 57. 20. 15.]]


In [85]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=82)

In [86]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [87]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[13. 32.  2. 85. 16.]
 [31. 66. 90. 25. 61.]
 [ 1. 64. 63. 48. 13.]
 [ 7. 80.  1. 87.  2.]]


In [88]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=54)

In [89]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [90]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[35. 52. 40. 18. 47.]
 [76. 52. 67. 61.  8.]
 [45. 47. 53. 32. 38.]
 [ 1. 64. 63. 48. 13.]]


In [91]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=55)

In [92]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [93]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[45. 47. 53. 32. 38.]
 [ 5. 60. 16. 32.  3.]
 [14. 83. 43. 48. 20.]
 [18. 72. 40. 46. 21.]]


In [94]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=56)

In [95]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [96]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[13. 32.  2. 85. 16.]
 [35. 52. 40. 18. 47.]
 [76. 52. 67. 61.  8.]
 [72. 26. 87.  6. 67.]]


In [97]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=57)

In [98]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [99]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[76. 52. 67. 61.  8.]
 [79.  3. 38. 53. 14.]
 [ 7. 80.  1. 87.  2.]
 [25. 90. 46. 24. 43.]]


In [100]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=58)

In [101]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [102]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[18. 72. 40. 46. 21.]
 [45. 47. 53. 32. 38.]
 [76. 52. 67. 61.  8.]
 [72. 26. 87.  6. 67.]]


In [103]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=59)

In [104]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [105]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[ 5. 60. 16. 32.  3.]
 [72. 26. 87.  6. 67.]
 [ 7. 80.  1. 87.  2.]
 [79.  3. 38. 53. 14.]]


In [106]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=60)

In [107]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [108]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[25. 90. 46. 24. 43.]
 [45. 47. 53. 32. 38.]
 [49.  7. 11. 46.  3.]
 [76. 52. 67. 61.  8.]]


In [109]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [110]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [111]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[35. 52. 40. 18. 47.]
 [31. 66. 90. 25. 61.]
 [79.  3. 38. 53. 14.]
 [ 1. 64. 63. 48. 13.]]


In [112]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [113]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [114]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[ 1. 64. 63. 48. 13.]
 [56. 26. 57. 38. 32.]
 [72. 26. 87.  6. 67.]
 [49.  7. 11. 46.  3.]]


In [115]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [116]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [117]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[14. 83. 43. 48. 20.]
 [ 7. 80.  1. 87.  2.]
 [25. 90. 46. 24. 43.]
 [32. 30. 41. 69. 52.]]


In [118]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [119]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [120]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[76. 52. 67. 61.  8.]
 [ 5. 60. 16. 32.  3.]
 [56. 26. 57. 38. 32.]
 [45. 47. 53. 32. 38.]]


In [121]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

In [122]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [123]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[79.  3. 38. 53. 14.]
 [35. 52. 40. 18. 47.]
 [ 4. 85. 34. 64. 43.]
 [76. 52. 67. 61.  8.]]


In [124]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [125]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [126]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[ 5. 60. 16. 32.  3.]
 [56. 26. 57. 38. 32.]
 [18. 72. 40. 46. 21.]
 [ 1. 64. 63. 48. 13.]]


In [127]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=6)

In [128]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [129]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[13. 32.  2. 85. 16.]
 [45. 47. 53. 32. 38.]
 [ 5. 60. 16. 32.  3.]
 [18. 72. 40. 46. 21.]]


In [130]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=8)

In [131]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [132]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[25. 90. 46. 24. 43.]
 [79.  3. 38. 53. 14.]
 [45. 47. 53. 32. 38.]
 [18. 72. 40. 46. 21.]]


In [133]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=200)

In [134]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [135]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[72. 26. 87.  6. 67.]
 [25. 90. 46. 24. 43.]
 [13. 32.  2. 85. 16.]
 [ 4. 85. 34. 64. 43.]]


In [136]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=500)

In [137]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [138]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[18. 72. 40. 46. 21.]
 [79.  3. 38. 53. 14.]
 [ 7. 80.  1. 87.  2.]
 [ 1. 64. 63. 48. 13.]]


In [139]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5000)

In [140]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [141]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[56. 24. 59. 32. 12.]
 [ 1. 64. 63. 48. 13.]
 [ 7. 80.  1. 87.  2.]
 [76. 52. 67. 61.  8.]]


In [142]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50000)

In [143]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [144]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[13. 32.  2. 85. 16.]
 [ 7. 80.  1. 87.  2.]
 [ 4. 85. 34. 64. 43.]
 [31. 66. 90. 25. 61.]]


In [145]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=6000)

In [146]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [150]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[56. 26. 57. 38. 32.]
 [ 5. 60. 16. 32.  3.]
 [13. 32.  2. 85. 16.]
 [49.  7. 11. 46.  3.]]


In [148]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [149]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [151]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [152]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[56. 26. 57. 38. 32.]
 [ 5. 60. 16. 32.  3.]
 [13. 32.  2. 85. 16.]
 [49.  7. 11. 46.  3.]]


In [153]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=8)

In [154]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [155]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[25. 90. 46. 24. 43.]
 [79.  3. 38. 53. 14.]
 [45. 47. 53. 32. 38.]
 [18. 72. 40. 46. 21.]]


In [156]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=9)

In [157]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [158]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[35. 52. 40. 18. 47.]
 [79.  3. 38. 53. 14.]
 [56. 24. 59. 32. 12.]
 [13. 32.  2. 85. 16.]]


In [159]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [160]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [161]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[35. 52. 40. 18. 47.]
 [56. 24. 59. 32. 12.]
 [ 4. 85. 34. 64. 43.]
 [13. 32.  2. 85. 16.]]


In [162]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

In [163]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [164]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[14. 83. 43. 48. 20.]
 [79.  3. 38. 53. 14.]
 [35. 52. 40. 18. 47.]
 [13. 32.  2. 85. 16.]]


In [165]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12)

In [166]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [167]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[49.  7. 11. 46.  3.]
 [10. 49. 57. 20. 15.]
 [14. 83. 43. 48. 20.]
 [56. 24. 59. 32. 12.]]


In [168]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=13)

In [169]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [170]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[18. 72. 40. 46. 21.]
 [72. 26. 87.  6. 67.]
 [31. 66. 90. 25. 61.]
 [56. 26. 57. 38. 32.]]


In [171]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=14)

In [172]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [173]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[31. 66. 90. 25. 61.]
 [13. 32.  2. 85. 16.]
 [ 5. 60. 16. 32.  3.]
 [56. 26. 57. 38. 32.]]


In [174]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15)

In [175]:
r = LinearRegression()
r.fit(X_train, y_train)

LinearRegression()

In [176]:
y_pred = r.predict(X_test)

print("y_pred:", y_pred)

y_pred: [[14. 83. 43. 48. 20.]
 [10. 49. 57. 20. 15.]
 [35. 52. 40. 18. 47.]
 [49.  7. 11. 46.  3.]]
