In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.DataFrame(np.array([[	
83,
44,
10,
53,
1], [43,
76,
87,
84,
19], [31,
66,
53,
68,
44], [79,
28,
60,
1,
62], [16,
62,
77,
47,
90], [5,
68,
45,
72,
10], [63,
10,
34,
67,
55], [66,
11,
76,
78,
85], [15,
38,
42,
86,
59], [81,
10,
32,
27,
1], [47,
51,
14,
87,
21], [57,
41,
77,
35,
56], [66,
16,
2,
85,
53], [88,
53,
4,
74,
34], [34,
4,
44,
9,
86], [30,
17,
47,
9,
18], [68,
52,
83,
63,
26], [81,
89,
18,
12,
37],[9,
44,
67,
77,
25]]), columns=list('ABCDE'))

In [4]:
df.head

<bound method NDFrame.head of      A   B   C   D   E
0   83  44  10  53   1
1   43  76  87  84  19
2   31  66  53  68  44
3   79  28  60   1  62
4   16  62  77  47  90
5    5  68  45  72  10
6   63  10  34  67  55
7   66  11  76  78  85
8   15  38  42  86  59
9   81  10  32  27   1
10  47  51  14  87  21
11  57  41  77  35  56
12  66  16   2  85  53
13  88  53   4  74  34
14  34   4  44   9  86
15  30  17  47   9  18
16  68  52  83  63  26
17  81  89  18  12  37
18   9  44  67  77  25>

In [5]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [6]:
number_of_rows = df.values.shape[0]
window_length = 7
number_of_features = df.values.shape[1]

In [7]:
train = np.empty([number_of_rows-window_length, window_length, number_of_features], dtype=float)

label = np.empty([number_of_rows-window_length, number_of_features], dtype=float)

window_length = 7

for i in range(0, number_of_rows-window_length):
    train[i]=transformed_df.iloc[i:i+window_length, 0: number_of_features]
    label[i]=transformed_df.iloc[i+window_length: i+window_length+1, 0: number_of_features]

In [8]:
train.shape

(12, 7, 5)

In [9]:
label.shape

(12, 5)

In [10]:
train[0]

array([[ 1.21411641,  0.12098052, -1.33558198, -0.04895644, -1.48896828],
       [-0.28625509,  1.43448332,  1.52945678,  1.0190193 , -0.82156703],
       [-0.73636654,  1.02401369,  0.26437473,  0.46780601,  0.10537914],
       [ 1.06407926, -0.53577088,  0.5248328 , -1.84039963,  0.77278039],
       [-1.29900585,  0.85982584,  1.15737383, -0.25566143,  1.81096011],
       [-1.71160802,  1.10610762, -0.03329163,  0.60560934, -1.15526766],
       [ 0.46393066, -1.2746162 , -0.44258288,  0.43335518,  0.51323546]])

In [11]:
train[1]

array([[-0.28625509,  1.43448332,  1.52945678,  1.0190193 , -0.82156703],
       [-0.73636654,  1.02401369,  0.26437473,  0.46780601,  0.10537914],
       [ 1.06407926, -0.53577088,  0.5248328 , -1.84039963,  0.77278039],
       [-1.29900585,  0.85982584,  1.15737383, -0.25566143,  1.81096011],
       [-1.71160802,  1.10610762, -0.03329163,  0.60560934, -1.15526766],
       [ 0.46393066, -1.2746162 , -0.44258288,  0.43335518,  0.51323546],
       [ 0.57645852, -1.23356924,  1.12016553,  0.81231432,  1.62557088]])

In [12]:
label[0]

array([ 0.57645852, -1.23356924,  1.12016553,  0.81231432,  1.62557088])

In [13]:
label[1]

array([-1.33651514, -0.12530125, -0.14491652,  1.08792096,  0.66154685])

In [14]:
from keras.models import Sequential
from keras. layers import LSTM, Dense, Bidirectional, Dropout
import numpy as np

batch_size = 100

In [15]:
model = Sequential()
model.add(Bidirectional(LSTM(240,
                            input_shape=(window_length, number_of_features),
                            return_sequences=True)))
model.add(Dropout(0.2))
model.add(Bidirectional(LSTM(240,
                            input_shape=(window_length, number_of_features),
                            return_sequences=True)))
model.add(Dropout(0.2))
model.add(Bidirectional(LSTM(240,
                            input_shape=(window_length, number_of_features),
                            return_sequences=True)))
model = Sequential()
model.add(Bidirectional(LSTM(240,
                            input_shape=(window_length, number_of_features),
                            return_sequences=False)))
model.add(Dense(59))
model.add(Dense(number_of_features))
model.compile(loss='mse', optimizer='rmsprop', metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [16]:
model.fit(train, label,
         batch_size=100, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.2500 - loss: 1.0094
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.2500 - loss: 0.8798
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.3333 - loss: 0.8091
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.4167 - loss: 0.7523
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.4167 - loss: 0.7013
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6528
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6055
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5833 - loss: 0.5584
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5833 - loss: 0.5116
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5833 - loss: 0.4654
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.4209
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step - accuracy: 0.6667 - loss: 0.3800
Ep

In [17]:
to_predict=np.array([[66,
16,
2,
85,
53], [88,
53,
4,
74,
34], [34,
4,
44,
9,
86], [30,
17,
47,
9,
18], [68,
52,
83,
63,
26], [81,
89,
18,
12,
37],[9,
44,
67,
77,
25]])
scaled_to_predict = scaler.transform(to_predict)


In [18]:
scaled_predicted_output_1 = model.predict(np.array([scaled_to_predict]))
print(scaler.inverse_transform(scaled_predicted_output_1).astype(int)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step
[109  51  53  31  31]
